"""Keyword dictionaries for mapping user language to structured preferences."""

GENRE_KEYWORDS = {
    "pop": "pop",
    "mainstream": "pop",
    "chart": "pop",
    "chart pop": "pop",
    "radio pop": "pop",
    "catchy": "pop",
    "lofi": "lofi",
    "lo-fi": "lofi",
    "chillhop": "lofi",
    "study beats": "lofi",
    "beats to study": "lofi",
    "rock": "rock",
    "hard rock": "rock",
    "guitar rock": "rock",
    "arena rock": "rock",
    "jazz": "jazz",
    "smooth jazz": "jazz",
    "swing": "jazz",
    "sax": "jazz",
    "ambient": "ambient",
    "atmospheric": "ambient",
    "soundscape": "ambient",
    "instrumental": "ambient",
    "electronic": "electronic",
    "edm": "electronic",
    "house": "electronic",
    "dance": "electronic",
    "techno": "electronic",
    "indie": "indie",
    "indie rock": "indie",
    "bedroom indie": "indie",
    "indie pop": "indie pop",
    "bedroom pop": "indie pop",
    "dream pop": "indie pop",
    "r&b": "r&b",
    "rnb": "r&b",
    "soul": "r&b",
    "neo soul": "r&b",
    "neo-soul": "r&b",
    "classical": "classical",
    "orchestral": "classical",
    "piano": "classical",
    "symphony": "classical",
    "metal": "metal",
    "heavy metal": "metal",
    "metalcore": "metal",
    "thrash": "metal",
    "synthwave": "synthwave",
    "retrowave": "synthwave",
    "retro wave": "synthwave",
    "outrun": "synthwave",
    "80s synth": "synthwave",
    "folk": "folk",
    "acoustic": "folk",
    "singer songwriter": "folk",
    "americana": "folk",
    "funk": "funk",
    "groovy": "funk",
    "disco funk": "funk",
    "bass groove": "funk",
    "alternative": "alternative",
    "alt": "alternative",
    "alt rock": "alternative",
    "grunge": "alternative",
    "world": "world",
    "global": "world",
    "international": "world",
    "worldbeat": "world",
}

MOOD_KEYWORDS = {
    "happy": "happy",
    "joyful": "happy",
    "cheerful": "happy",
    "uplifting": "happy",
    "bright": "happy",
    "sunny": "happy",
    "feel good": "happy",
    "chill": "chill",
    "laid back": "chill",
    "laid-back": "chill",
    "mellow": "chill",
    "easygoing": "chill",
    "breezy": "chill",
    "relaxed": "relaxed",
    "calm": "relaxed",
    "peaceful": "relaxed",
    "soothing": "relaxed",
    "gentle": "relaxed",
    "quiet": "relaxed",
    "focus": "focused",
    "focused": "focused",
    "study": "focused",
    "studying": "focused",
    "concentration": "focused",
    "productive": "focused",
    "deep work": "focused",
    "reading": "focused",
    "intense": "intense",
    "aggressive": "intense",
    "furious": "intense",
    "explosive": "intense",
    "heavy": "intense",
    "energetic": "energetic",
    "energy": "energetic",
    "upbeat": "energetic",
    "hyped": "energetic",
    "pumped": "energetic",
    "fired up": "energetic",
    "adrenaline": "energetic",
    "moody": "moody",
    "dark": "moody",
    "brooding": "moody",
    "nocturnal": "moody",
    "dreamy": "moody",
    "introspective": "moody",
    "melancholy": "melancholy",
    "sad": "melancholy",
    "heartbroken": "melancholy",
    "wistful": "melancholy",
    "somber": "melancholy",
    "blue": "melancholy",
    "lonely": "melancholy",
    "relaxing": "relaxed",
    "vibes": "chill",
    "vibe": "chill",
    "vibing": "chill",
}

ENERGY_KEYWORDS = {
    "sleep": 0.15,
    "sleepy": 0.2,
    "dreamy": 0.2,
    "ambient": 0.25,
    "calm": 0.3,
    "soft": 0.3,
    "gentle": 0.3,
    "peaceful": 0.3,
    "chill": 0.35,
    "laid back": 0.35,
    "mellow": 0.35,
    "easy": 0.35,
    "relaxed": 0.4,
    "focused": 0.45,
    "study": 0.4,
    "studying": 0.4,
    "background": 0.4,
    "reading": 0.4,
    "groove": 0.5,
    "steady": 0.5,
    "medium": 0.55,
    "balanced": 0.55,
    "moderate": 0.55,
    "upbeat": 0.7,
    "happy": 0.7,
    "dance": 0.72,
    "party": 0.78,
    "driving": 0.75,
    "run": 0.8,
    "running": 0.8,
    "hype": 0.82,
    "energetic": 0.85,
    "power": 0.88,
    "workout": 0.9,
    "gym": 0.9,
    "training": 0.9,
    "intense": 0.95,
    "aggressive": 0.95,
    "explosive": 0.95,
    "relaxing": 0.35,
    "vibe": 0.4,
    "vibes": 0.4,
}